import keyMirror from 'key-mirror'

export default keyMirror({

  // App alert
  SHOW_ALERT_MESSAGE: null,
  DISMISS_ALERT_MESSAGE: null,

  // Page form types
  PAGE_MAIN_FORM: null,
  PAGE_MAIN_FORM_WITH_PHOTO_OVERLAY: null,
  PAGE_PHOTOS_BROWSER_FORM: null,
  PAGE_PHOTOS_BROWSER_FORM_WITH_PHOTO_OVERLAY: null,
  PAGE_EDIT_FORM: null,
  PAGE_NEW_FORM: null,
  PAGE_OVERLAY_SELECTED_PHOTO_FORM: null,
  PAGE_SINGLE_SELECTED_PHOTO_FORM: null,

  // Home More Menus
  MENU_ITEM_ADD_OR_EDIT_RESTAURANT: null,
  MENU_ITEM_ADD_OR_EDIT_EVENT: null,
  MENU_ITEM_ADD_OR_EDIT_RECIPE: null,
  MENU_ITEM_ADD_OR_EDIT_USER: null,
  MENU_ITEM_ADD_OR_EDIT_REVIEW: null,
  MENU_ITEM_SEARCH_RESTAURANTS: null,
  MENU_ITEM_MANAGE_FRIENDS: null,
  MENU_ITEM_READ_REVIEWS: null,

  // Model Form Mode
  MODEL_FORM_TYPE_NEW: null,
  MODEL_FORM_TYPE_EDIT: null,

  // Edit Model
  EDIT_MODEL_TOGGLE_TYPE: null,
  ON_EDIT_MODEL_FORM_FIELD_CHANGE: null,
  UPDATE_MODEL_REQUEST: null,
  SAVED_MODEL_REQUEST: null,
  UPDATE_MODEL_SUCCESS: null,
  UPDATE_MODEL_FAILURE: null,

  // Parse Object
  PARSE_CONFIGURE: null,
  PARSE_RECORDS: null,
  PARSE_RESTAURANTS: null,
  PARSE_EVENTS: null,
  PARSE_PEOPLE_IN_EVENTS: null,
  PARSE_USERS: null,
  PARSE_PHOTOS: null,
  PARSE_RECIPES: null,
  PARSE_REVIEWS: null,

  // Login UI
  LOGIN_FORM_TYPE_MAIN: null,
  LOGIN_FORM_TYPE_LOGIN: null,
  LOGIN_FORM_TYPE_REGISTER: null,
  LOGIN_FORM_TYPE_FORGOTPASSWORD: null,
  LOGIN_FORM_TYPE_RESET_PASSWD: null,


  // User Profile Type
  USERPROFILE_TYPE_UPVOTE: null,
  USERPROFILE_TYPE_DOWNVOTE: null,
  USERPROFILE_TYPE_SUBMITTED_POSTS: null,
  USERPROFILE_TYPE_FOLDER_LIST: null,

  // UserProfile Event Type
  USERPROFILE_RESET: null,
  USERPROFILE_LOADED: null,

  // Voting button types
  VOTE_BUTTON_LIST_UPVOTE: null,
  VOTE_BUTTON_LIST_DOWNVOTE: null,
  VOTE_BUTTON_ARTICLE_UPVOTE: null,
  VOTE_BUTTON_ARTICLE_DOWNVOTE: null,
  VOTE_BUTTON_RELATED_UPVOTE: null,
  VOTE_BUTTON_RELATED_DOWNVOTE: null,


  // Voting
  POSTS_UPVOTE: null,
  POSTS_DOWNVOTE: null,
  POSTS_UPVOTE_CACEL: null,
  POSTS_DOWNVOTE_CACEL: null,

  POSTS_VOTING_DONE: null,

  // Users
  LOGGED_IN: null,
  LOGGED_OUT: null,
  SET_SHARING: null,
  RESET_NUXES: null,


  // For dashboard
  DASHBOARD_EDIT_ALL_ROWS: null,
  DASHBOARD_EDIT_SINGLE_ROW: null,
  DASHBOARD_EDIT_SINGLE_ROW_CANCEL: null,

  TOGGLE_TABLE_ROW_CHECKBOX: null,
  TOGGLE_TABLE_ROW_ALL_CHECKBOXS: null,

  DASHBOARD_LOADED_PAGINATION: null,
  DASHBOARD_LOADED_TOPICS: null,
  DASHBOARD_RESET: null,

  // PostHome, PostDaily
  LIST_VIEW_LOADED_BY_TYPE: null,
  LIST_VIEW_LOADED_RESTAURANTS: null,
  LIST_VIEW_LOADED_EVENTS: null,
  LIST_VIEW_LOADED_ORDERED_USERS: null,
  LIST_VIEW_LOADED_RECIPES: null,
  LIST_VIEW_LOADED_USERS: null,
  LIST_VIEW_RESET_ALL_POSTS: null,
  LOADED_PHOTOS_BROWSER: null,

  // Detailed Page(Posts,Events)
  OVERLAY_LOADED_MODEL_PAGE: null,
  OVERLAY_LOADED_MODEL_RESET: null,

  SET_PLATFORM: null,
  SET_VERSION: null,

  LOGIN_VIA_SOCIAL: null,

  ON_LOGIN_STATE_CHANGE: null,
  LOGOUT: null,

  ON_AUTH_FORM_FIELD_CHANGE: null,
  REQUEST_API: null,
  RESET_ERROR: null,
  SIGNUP_REQUEST: null,
  SIGNUP_SUCCESS: null,
  SIGNUP_FAILURE: null,

  LOGIN_REQUEST: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,

  LOGOUT_REQUEST: null,
  LOGOUT_SUCCESS: null,
  LOGOUT_FAILURE: null,

  SET_SESSION_TOKEN: null,

  RESET_PASSWORD_REQUEST: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILURE: null,

  GET_PROFILE_REQUEST: null,
  GET_PROFILE_SUCCESS: null,
  GET_PROFILE_FAILURE: null,

  ON_PROFILE_FORM_FIELD_CHANGE: null,

  PROFILE_UPDATE_REQUEST: null,
  PROFILE_UPDATE_SUCCESS: null,
  PROFILE_UPDATE_FAILURE: null,

  SET_STATE: null,
  GET_STATE: null,
  SET_STORE: null,

  FORGOT_PASSWORD: null,
  LOGIN: null,
  REGISTER: null,

  ON_SHIPMENT_FORM_FIELD_CHANGE: null,
  NEW_SHIPMENT: null,
  NEW_SHIPMENT_REQUEST: null,
  NEW_SHIPMENT_SUCCESS: null,
  NEW_SHIPMENT_FAILURE: null,

  GET_SHIPMENTS_REQUEST: null,
  GET_SHIPMENTS_SUCCESS: null,
  GET_SHIPMENTS_FAILURE: null,

  ON_SHIPMENT_SAVED: null

})
